'use client';
import { FavoriteFilled } from '@carbon/icons-react';
import './_contributors.scss';
import { Button } from '@carbon/react';
import CtaSection from '../../CtaSection';

export default function Contributors() {
  // This would typically come from an API or database
  const contributors = [
    'Zaire Curtis',
    'Marley Ekstrom Bothman',
    'Rico Bator',
    'Jordyn Mango',
    'Zain Rhiel Madsen',
    'Maria Septimus',
    'Lydia Ekstrom Bothman',
    'Skylar Dokidis',
    'Brandon Bator',
    'Marcus Dorin',
    'Tatiana Lubin',
    'Jayden George',
    'Marcus Herowitz',
    'Abram Septimus',
    'Zain Diem',
    'Angel Bator',
    'Lincoln Passaquindici Arcand',
    'Alfonso Sighton',
    'Madelyn Bias',
    'Gretchen Bator',
    'Justin Botson',
    'Abram Vaccaro',
    'Tiana Geldt',
    'Ahmad Geldt',
    'Kaylynn Bergson',
    'Makenna George',
    'Hanna Botson',
    'Kaylynn George',
    'Lincoln Baptista',
    'Corey Vaccaro',
    'Zain Diem',
    'Erin Stanton',
    'Jayden Geldt',
    'Emerson Aminoff',
    'Lydia Phillips',
    'Jordyn Lubin',
    'Randy Bator',
    'Zain Rhiel Madsen',
    'Davis Diem',
    'Zaira Moreman',
    'Zaire Geldt',
    'James Dorin',
    'Marlie Ekstrom Bothman',
    'Brandon Vaccaro',
    'Alfonso Lubin',
    'Jordyn Press',
    'Alfredo Phillips',
    'Marley Geldt',
    'Marissa Ekstrom Bothman',
    'Lindsey Bias',
    'Maria Bator',
    'Philip Rhiel Madsen',
    'Nolan Vaccaro',
    'Chance Rosser',
    'Alfredo Franzi',
    'Jayden Rosser',
    'Chance Stewart',
    'Angel Baptista',
    'Zaire Vetrovs',
    'Marcus Baptista',
    'Gretchen Herowitz',
    'Nolan Phillips',
    'Lindsey Westervelt',
    'Jason Rosser',
    'Haylie Davis',
    'Alice Kentez',
    'Kianna Madsen',
    'Skylar Geldt',
    'Cheyenne Baptista',
    'Kiarra Stanton',
    'Ahmad Geldt',
    'Lincoln Baptista',
    'Marcus Bator',
    'Tatiana Lubin',
    'Marilyn Sighton',
    'Erin Herowitz',
    'Brandon Vaccaro',
    'Tatiana Vaccaro',
    'Jordyn Baptista',
    'Justin Aminoff',
    'Zain Kentez',
    'Jayden Sighton',
    'Tatiana Stanton',
    'Emerson Bergson',
    'Jayson Korgaard',
    'Lydia Levin',
    'Anike Franzi',
    'Carter Taeff',
    'Carla Taeff',
    'Maria Septimus',
    'Kaylynn Dokidis',
    'Kathryn Stanton',
    'Alana Vaccaro',
    'Angel Bergson',
    'Kianna Baptista',
    'Alana Phillips',
    'Marley Kentez',
    'Alana Kentez',
    'Chance Westervelt',
    'Charlie Bergson',
    'Zain Dokidis',
    'Alfonso Geldt',
    'Erin Calzoni',
    'Omar Lubin',
    'Marcus Rhiel Madsen',
    'Nolan Phillips',
    'Justin Dokidis',
    'Lydia Westervelt',
    'Livia Korgaard',
    'Carla Lubin',
    'Alana Botson',
    'Kaylynn Geldt',
    'Madelyn Dorin',
    'Talan Franzi',
    'Erin Lubin',
    'Omar Stanton',
    'Zain Lubin',
    'Skylar Geldt',
    'Talan Rhiel Madsen',
    'Talan Levin',
    'Randy Dokidis',
    'Jocelyn Dorin',
    'Cheyenne Passaquindici Arcand',
    'Randy Cardoz',
    'Ruben Rosser',
    'Martin Ekstrom Bothman',
    'Jocelyn Lubin',
    'Rico Phillips',
    'Aliya Botson',
    'Angel Kentez',
    'Tiana Scheffler',
    'Maria Cathane',
    'Jakob Press',
    'Kierra Saris',
    'Jocelyn Gowan',
    'Roger Stanton',
    'Zain Phillips',
    'Ryan Ekstrom Bothman',
    'Cooper Lubin',
    'Corey Westervelt',
    'Ryan Korgaard',
    'Kaylynn Saris',
    'Madelyn Dorin',
    'Marcus Stanton',
    'Maria Herowitz',
    'Kianna Herowitz',
    'Lydia Bator',
    'Livia Gowan',
    'Kianna Gowan',
    'Randy Sighton',
    'Justin Botson',
    'Zain Bergson',
    'Roger Saris',
    'Ahmad Westervelt',
    'Tatiana Gowan',
    'Alfredo Curtis',
    'Marcus Calzoni',
    'Lincoln Franzi',
    'Kaylynn Lubin',
    'Kaylynn Calzoni',
    'Talan Baptista',
    'Alana Gowan',
    'Ann Bator',
    'Jakob Septimus',
    'Lydia Rosser',
    'Cheyenne Dokidis',
    'Jordyn Gowan',
    'Kianna Phillips',
    'Ahmad Calzoni',
    'Roger Taeff',
    'Jayden Korgaard',
    'Tatiana Kentez',
    'Martin Septimus',
    'Livia Ekstrom Bothman',
    'Karen Lubin',
    'Terry Calzoni',
    'Omar George',
    'Marilyn Dorin',
    'Karen Sighton',
    'Ahmad Gowan',
    'Jordyn Gowan',
    'Kaiya Levin',
    'Kianna Cathner',
    'Zaire Franzi',
    'Craig Geldt',
    'Lou Moreman',
    'Patlyn Lubin',
    'Carla Stanton',
    'Marcus Press',
    'Jordyn Liashitz',
    'Tatiana Geldt',
    'Maria Rhiel Madsen',
    'Hanna Gowan',
    'Hanna Saris',
    'Marley Westervelt',
    'Marcus Calzoni',
    'Rico Bator',
    'Patlyn Passaquindici Arcand',
    'Marley Baptista',
    'Makenna Bergson',
    'Jakob Vaccaro',
    'Giana Lubin',
    'Jordyn Sighton',
    'Kaylynn Press',
    'Anike Aminoff',
    'Cooper Ekstrom Bothman',
    'Alana Moreman',
    'Nolan Phillips',
    'Marcus Dias',
    'Marley Baptista',
    'Cheyenne Vetrovs',
    'Philip Westervelt',
    'Carter Westervelt',
    'Kaiya Press',
    'Lou Stanton',
    'Dulce Kentez',
    'James Kentez',
    'Omar Dokidis',
    'Maria Bator',
    'Abram Dias',
    'Kaiya Dokidis',
    'Aspen Baptista',
    'Kaylynn Curtis',
    'Anike Lipton',
    'Zaire Westervelt',
    'Skylar Phillips',
    'Lou Westervelt',
    'Karen Phillips',
    'Ahmad Baptista',
    'Jayson Sighton',
    'Charlie Bergson',
    'Alfredo Ahmad Madsen',
    'Nolan Vetrovs',
    'Carla Taeff',
    'Jocelyn Cathne',
    'Lindsey Scheffler',
    'Talan Dias',
    'Jayden Mango',
    'Rayna Herowitz',
    'Roger Sighton',
    'Corey Levin',
    'Davis Franzi',
    'Tiana Vetrovs',
    'Skylar Taeff',
    'Tatiana Calzoni',
    'Alana Liashitz',
    'Jocelyn Gowan',
    'Carter Sighton',
    'Skylar Webman',
    'Alfredo Franzi',
    'Craig Vetrovs',
    'Cooper Phillips',
    'Emerson Levin',
    'Jordyn Franzi',
    'Wilson Sighton',
    'Kaylynn Moreman',
    'Ruben Geldt',
    'Angel Septimus',
    'Abram Moreman',
    'Cooper Vaccaro',
    'Kaylynn Rhiel Madsen',
    'Kianna Bergson',
    'Davis Vaccaro',
    'Corey Vetrovs',
    'Marilyn Gowan',
    'Abram Passaquindici Arcand',
    'Karen Dokidis',
    'Aspen Taeff',
    'Marley Rhiel Madsen',
    'Corey Gowan',
    'Nolan Gowan',
  ];

  return (
    <>
      <section className="contributors-section">
        <div className="contributors-container">
          <div className="heart-icon">
            <FavoriteFilled size={32} className="heart" />
          </div>

          <h2 className="contributors-title">
            A heartfelt thanks to the early supporters who hold Giga Blocks NFTs
            and power our movement. Below are just a few wallet addresses
            belonging to incredible individuals who believe in universal
            connectivity
          </h2>

          <p className="contributors-description">
            Your commitment ensures schools are no longer invisible and students
            everywhere have the chance to thrive in the digital age. Ready to
            get involved? By supporting Giga Blocks, you join a global effort to
            bring every school onto the blockchain, and every student into the
            online world.
          </p>

          <div className="contributors-grid">
            {contributors.map((contributor, index) => (
              <span key={index} className="contributor-name">
                {contributor}
              </span>
            ))}
          </div>

          <p className="contributors-more">and many more.</p>
        </div>
      </section>
      <section className="cta-section">
        <CtaSection
          title={`Be a part of a bigger initiative. Activate a school today.`}
        />
      </section>
    </>
  );
}
