apiVersion: v1
kind: Secret
metadata:
  name: giga-helm-secret
data:
  api: >-
    YXBpLWVudg==
  deltasharing: >-
    ZGVsdGFzaC1zaGFyaW5n
  deltasharing-creds: >-
    ZGVsdGFzaC1zaGFyaW5nLWNyZWRz
  deltasharing-qos-creds: >-
    ZGVsdGFzaC1zaGFyaW5nLWNvcy1jcmVkcw==
  redis-password: cmVkZGlzUGFzc3dk # Base64-encoded: reddisPasswd
  rabbitmq-password: cmFiYml0bXEtc2VjcmV0 # Base64-encoded: rabbitmq-secret
  postgresql-app-userpassword: YXBwVXNlclBhc3N3ZA== # Base64-encoded: appUserPasswd
  postgresql-app-adminpassword: YXBwQWRtaW5QYXNzd2Q=
 # Base64-encoded: appAdminPasswd
  postgresql-newsletter-userpassword: bmV3c1VzZXJQYXNzd2Q= # Base64-encoded: newsUserPasswd
  postgresql-newsletter-adminpassword: bmV3c0FkbWluUGFzc3dk # Base64-encoded: newsAdminPasswd
  webhook: >-
    d2ViaG9vay1zZWN1cml0eS1zZWNyZXQ= 

type: Opaque
