replicaCount: 1

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""
environment: &env "dev"
namespace: giga-blocks

# Chart Postgresql dependency
global:
  postgresql-app:
    architecture: standalone
    name: giga-blocks
    service:
      ports:
        postgresql: &dbport_app "5432"
    auth:
      enablePostgresUser: true
      username: &dbuser_app "dbuser"
      database: &db_app "app"
      existingSecret: giga-blocks-secret
      secretKeys:
        adminPasswordKey: postgresql-app-adminpassword
        userPasswordKey: postgresql-app-userpassword

  postgresql-newsletter:
    architecture: standalone
    name: giga-blocks
    service:
      ports:
        postgresql: &dbport_news "5432"
    auth:
      enablePostgresUser: true
      username: &dbuser_news "dbuser2"
      database: &db_news "newsletter"
      existingSecret: giga-blocks-secret
      secretKeys:
        adminPasswordKey: postgresql-newsletter-adminpassword
        userPasswordKey: postgresql-newsletter-userpassword

postgresql-app:
  enabled: true
  serviceAccount:
    create: false
  auth:
    enablePostgresUser: true
    username: &dbuser_app "dbuser"
    database: &db_app "app"
    existingSecret: giga-blocks-secret
    secretKeys:
      adminPasswordKey: postgresql-app-adminpassword
      userPasswordKey: postgresql-app-userpassword
  primary:
    networkPolicy:
      enabled: false
    pgHbaConfiguration: |-
      local all all trust
      host all all localhost trust
      host all all 0.0.0.0/0 trust
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 50Mi
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
      storageClass:
    securityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: ["ALL"]
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: 0
    shmVolume:
      chmod:
        enabled: false
  serviceName: "{{ .Release.Name }}-postgresql-app"


postgresql-newsletter:
  enabled: true
  serviceAccount:
    create: false
  auth:
    enablePostgresUser: true
    username: &dbuser_news "dbuser2"
    database: &db_news "newsletter"
    existingSecret: giga-blocks-secret
    secretKeys:
      adminPasswordKey: postgresql-newsletter-adminpassword
      userPasswordKey: postgresql-newsletter-userpassword
  primary:
    networkPolicy:
      enabled: false
    pgHbaConfiguration: |-
      local all all trust
      host all all localhost trust
      host all all 0.0.0.0/0 trust
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 50Mi
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
      storageClass:
    securityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: ["ALL"]
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: 0
    shmVolume:
      chmod:
        enabled: false
  serviceName: "{{ .Release.Name }}-postgresql-newsletter"

# Redis
redis:
  enabled: true
  architecture: standalone
  auth:
    existingSecret: giga-blocks-secret
    existingSecretPasswordKey: redis-password
  networkPolicy:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  serviceName: "{{ .Release.Name }}-redis"

# Rabbitmq
rabbitmq:
  enabled: true
  auth:
    username: user
    existingPasswordSecret: giga-blocks-secret
    secretKeys:
      rabbitmqPasswordKey: rabbitmq-password
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"
  serviceName: "{{ .Release.Name }}-rabbitmq"

api:
  fullname: giga-chart-api
  labels:
    app: giga-chart-api
  image:
    repository: "rumsan/giga-mono-ntf2-api"
    tag: "stage-1d88a04"
    pullPolicy: Always
    secrets: 
      - name: "imagePullCreds"
  args:
    - |
      cp /usr/src/vault/env /usr/src/app/.env
      node main.js
  # args:
  #   - |
  #     cp /usr/src/vault/env /usr/src/app/.env
  #     sleep 500
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  replicas: 1
  service:
    type: ClusterIP
    port: 8000
    targetPort: 3333
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configVolume: { }
  secretName: giga-blocks-secret
  resources:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 128Mi
  livenessProbe:
    httpGet:
      path: /api/v1/auth/ping
      port: http
    periodSeconds: 20
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /api/v1/auth/ping
      port: http
    periodSeconds: 20
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3

web:
  fullname: giga-chart-web
  labels:
    app: giga-chart-web
  image:
    repository: "rumsan/giga-helm-web"
    tag: "stage"
    pullPolicy: Always
    secrets: 
      - name: "imagePullCreds"
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 8000
    targetPort: 3000
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configVolume: { }
  resources:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 128Mi
  livenessProbe: { }
  readinessProbe: { }


webhook:
  fullname: giga-chart-webhook
  labels:
    app: giga-chart-webhook
  image:
    repository: "rumsan/giga-mono-ntf2-webhook"
    tag: "stage-b854c5d-157"
    pullPolicy: Always
    secrets: 
      - name: "imagePullCreds"
  args:
    - |
      cp /usr/src/vault/env /usr/src/app/.env
      set -a
      source /usr/src/app/.env
      set +a
      node main.js
  # args:
  #   - |
  #     cp /usr/src/vault/env /usr/src/app/.env
  #     set -a
  #     source /usr/src/app/.env
  #     set +a
  #     sleep 500
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 8000
    targetPort: 3010
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configVolume: { }
  secretName: giga-blocks-secret
  resources:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 128Mi
  livenessProbe: { }
  readinessProbe: { }

admin:
  fullname: giga-chart-admin
  labels:
    app: giga-chart-admin
  environment:
    - name: NEXT_PUBLIC_ADMIN_BASE_PATH
      value: "/admin"
  image:
    repository: "rumsan/giga-helm-admin"
    tag: "stage"
    pullPolicy: Always
    secrets: 
      - name: "imagePullCreds"
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 8000
    targetPort: 3000
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configVolume: { }
  resources:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 128Mi
  livenessProbe: { }
  readinessProbe: { }

ingress:
  enabled: true
  pathType: Prefix
  host: "giga-blocks.local"
  web:
    path: "/"
    backendService: "giga-chart-web-svc"
  api:
    path: "/api/v1"
    backendService: "giga-chart-api-svc"
  admin:
    path: "/admin"
    backendService: "giga-chart-admin-svc"
  webhook:
    path: "/webhook"
    backendService: "giga-chart-webhook-svc"
  # docs:
  #   path: "/doc"
  #   backendService: "giga-blocks-docs"