replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
environment: &env "dev"
namespace: rahat
# Chart Postgresql dependency
# global:
#   postgresql-app:
#     architecture: standalone
#     name: giga-helm
#     service:
#       ports:
#         postgresql: &dbport_app "5432"
#     auth:
#       enablePostgresUser: true
#       username: &dbuser_app "rumsan"
#       database: &db_app "app"
#       existingSecret: giga-helm-secret
#       secretKeys:
#         adminPasswordKey: postgresql-app-adminpassword
#         userPasswordKey: postgresql-app-userpassword

#   postgresql-newsletter:
#     architecture: standalone
#     name: giga-helm
#     service:
#       ports:
#         postgresql: &dbport_news "5432"
#     auth:
#       enablePostgresUser: true
#       username: &dbuser_news "rumsan"
#       database: &db_news "newsletter"
#       existingSecret: giga-helm-secret
#       secretKeys:
#         adminPasswordKey: postgresql-newsletter-adminpassword
#         userPasswordKey: postgresql-newsletter-userpassword
postgresql-app:
  enabled: true
  serviceAccount:
    create: false
  auth:
    enablePostgresUser: true
    username: "rumsan"
    database: "app"
    existingSecret: giga-helm-secret
    secretKeys:
      adminPasswordKey: postgresql-app-adminpassword
      userPasswordKey: postgresql-app-userpassword
  primary:
    # configuration: |-
    #   shared_buffers = '3GB'
    #   work_mem = '64MB'
    #   maintenance_work_mem = '1GB'
    #   wal_buffers = '16MB'
    #   max_wal_size = '4GB'
    #   min_wal_size = '2GB'
    #   checkpoint_timeout = '15min'
    #   max_worker_processes = 60
    #   max_connections = 500
    #   max_prepared_transactions = 100
    networkPolicy:
      enabled: false
    pgHbaConfiguration: |-
      local all all trust
      host all all localhost trust
      host all all 0.0.0.0/0 trust
    resources:
      requests:
        memory: "5Gi"
        cpu: "500m"
      limits:
        memory: "7Gi"
        cpu: "1500m"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
      storageClass:
    securityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: ["ALL"]
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: 0
    shmVolume:
      chmod:
        enabled: false
  serviceName: "{{ .Release.Name }}-postgresql-app"
# PostgreSQL Newsletter Database Configuration
postgresql-newsletter:
  enabled: true
  serviceAccount:
    create: false
  auth:
    enablePostgresUser: true
    username: "rumsan"
    database: "newsletter"
    existingSecret: giga-helm-secret
    secretKeys:
      adminPasswordKey: postgresql-newsletter-adminpassword
      userPasswordKey: postgresql-newsletter-userpassword
  primary:
    networkPolicy:
      enabled: false
    pgHbaConfiguration: |-
      local all all trust
      host all all localhost trust
      host all all 0.0.0.0/0 trust
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 50Mi
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
      storageClass:
    securityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: ["ALL"]
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: 0
    shmVolume:
      chmod:
        enabled: false
  serviceName: "{{ .Release.Name }}-postgresql-newsletter"
# Redis
redis:
  enabled: true
  architecture: standalone
  auth:
    existingSecret: giga-helm-secret
    existingSecretPasswordKey: redis-password
  networkPolicy:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        cpu: "100m"
        memory: "350Mi"
      limits:
        cpu: "500m"
        memory: "800Mi"
  serviceName: "{{ .Release.Name }}-redis"
# Rabbitmq
rabbitmq:
  enabled: true
  auth:
    username: user
    existingPasswordSecret: giga-helm-secret
    secretKeys:
      rabbitmqPasswordKey: rabbitmq-password
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      cpu: "100m"
      memory: "150Mi"
    limits:
      cpu: "500m"
      memory: "300Mi"
  serviceName: "{{ .Release.Name }}-rabbitmq"
api:
  fullname: giga-helm-api
  labels:
    app: giga-helm-api
  image:
    repository: "rumsan/giga-mono-ntf2-api"
    tag: "stage-bd6afb6-161"
    pullPolicy: Always
    secrets:
      - name: "rumsan-docker-creds"
  args:
    - |
      cp /usr/src/vault/env /usr/src/app/.env
      node main.js
  # args:
  #   - |
  #     cp /usr/src/vault/env /usr/src/app/.env
  #     sleep 500
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  replicas: 1
  service:
    type: ClusterIP
    port: 8000
    targetPort: 3333
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  configVolume: {}
  secretName: giga-helm-secret
  resources:
    requests:
      cpu: "250m"
      memory: "550Mi"
    limits:
      cpu: "1000m"
      memory: "1500Mi"
  livenessProbe:
    httpGet:
      path: /api/v1/auth/ping
      port: http
    periodSeconds: 20
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /api/v1/auth/ping
      port: http
    periodSeconds: 20
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3
web:
  fullname: giga-helm-web
  labels:
    app: giga-helm-web
  image:
    repository: "rumsan/giga-helm-web"
    tag: "stage-bd6afb6-161"
    pullPolicy: Always
    secrets:
      - name: "rumsan-docker-creds"
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 8000
    targetPort: 3000
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  configVolume: {}
  resources:
    requests:
      cpu: 500m
      memory: 700Mi
    limits:
      cpu: 1500m
      memory: 1400Mi
  livenessProbe: {}
  readinessProbe: {}
admin:
  fullname: giga-helm-admin
  labels:
    app: giga-helm-admin
  environment:
    - name: NEXT_PUBLIC_ADMIN_BASE_PATH
      value: "/admin"
  image:
    repository: "rumsan/giga-helm-admin"
    tag: "stage-bd6afb6-161"
    pullPolicy: Always
    secrets:
      - name: "rumsan-docker-creds"
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 8000
    targetPort: 3000
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  configVolume: {}
  resources:
    requests:
      cpu: 500m
      memory: 700Mi
    limits:
      cpu: 1500m
      memory: 1400Mi
  livenessProbe: {}
  readinessProbe: {}
webhook:
  fullname: giga-helm-webhook
  labels:
    app: giga-helm-webhook
  image:
    repository: "rumsan/giga-mono-ntf2-webhook"
    tag: "stage-bd6afb6-161"
    pullPolicy: Always
    secrets:
      - name: "rumsan-docker-creds"
  args:
    - |
      cp /usr/src/vault/env /usr/src/app/.env
      set -a
      source /usr/src/app/.env
      set +a
      node main.js
  # args:
  #   - |
  #     cp /usr/src/vault/env /usr/src/app/.env
  #     set -a
  #     source /usr/src/app/.env
  #     set +a
  #     sleep 500
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 8000
    targetPort: 3010
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  configVolume: {}
  secretName: giga-helm-secret
  resources:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 128Mi
  livenessProbe: {}
  readinessProbe: {}
ingress:
  enabled: true
  pathType: Prefix
  host: "helm-giga.rumsan.net"
  web:
    path: "/"
    backendService: "giga-helm-web-svc"
  api:
    path: "/api/v1"
    backendService: "giga-helm-api-svc"
  admin:
    path: "/admin"
    backendService: "giga-helm-admin-svc"
  webhook:
    path: "/webhook"
    backendService: "giga-helm-webhook-svc"

