export const MAIL_QUEUE = 'MAIL_QUEUE';
export const SENT_OTP = 'SENT_OTP';
export const WELCOME_MSG = 'WELCOME_MSG';
export const NEWSLETTER_WELCOME = 'NEWSLETTER_WELCOME';
export const DEVELOPER_JOIN_MAIL = 'DEVELOPER_JOIN_MAIL';
export const DATA_VALIDATION = 'DATA_VALIDATION';
