export const MINT_QUEUE = 'MINT_QUEUE';
export const ONCHAIN_DATA_QUEUE = 'ONCHAIN_DATA_QUEUE';
export const SET_ONCHAIN_DATA = 'SET_ONCHAIN_DATA';
export const SET_MINT_NFT = 'SET_MINT_NFT';
export const SET_MINT_SINGLE_NFT = 'SET_MINT_SINGLE_NFT';
