# Install dependencies only when needed
FROM node:18-alpine3.17 AS deps
WORKDIR /usr/src/app
COPY ./dist/apps/web/package.json ./
RUN cat package.json
RUN yarn install 


FROM node:18-alpine3.17 AS builder
WORKDIR /usr/src/app
COPY ./dist/apps/web/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
CMD [ "npm", "start" ]`