FROM node:20-alpine3.17 AS base
WORKDIR /usr/src/app

# Install dependencies only when needed
FROM base AS deps
COPY ./dist/apps/webhook/package.json ./
RUN npm install 

FROM base AS builder
COPY ./dist/apps/webhook/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
CMD [ "npm", "start" ]