FROM node:20-alpine3.17 AS base
WORKDIR /usr/src/app
RUN npm install -g sharp

# Install dependencies only when needed
FROM base AS deps
WORKDIR /usr/src/app
COPY ./dist/apps/giga/package.json ./
RUN npm install -g pnpm@8.14.1 && pnpm i

FROM base AS builder
WORKDIR /usr/src/app
COPY ./dist/apps/giga/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
CMD [ "npm", "start" ]