FROM node:20-alpine3.17 AS base
WORKDIR /usr/src/app
RUN npm install -g sharp

# Install dependencies only when needed
FROM base AS deps
WORKDIR /usr/src/app
COPY ./dist/apps/web/package.json ./
RUN yarn install 


FROM base AS builder
WORKDIR /usr/src/app
COPY ./dist/apps/web/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
CMD [ "npm", "start" ]`