# Install dependencies only when needed
FROM node:20-alpine3.17 AS deps
WORKDIR /usr/src/app
COPY ./dist/apps/giga/package.json ./
RUN npm install -g pnpm@8.14.1 && pnpm i

FROM node:20-alpine3.17 AS builder
WORKDIR /usr/src/app
COPY ./dist/apps/giga/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
CMD [ "npm", "start" ]