# Install dependencies only when needed
FROM node:18-alpine3.17 AS deps
WORKDIR /usr/src/app
COPY ./dist/apps/api/package.json ./
RUN npm install 

FROM node:18-alpine3.17 AS builder
RUN apk --no-cache add chromium
WORKDIR /usr/src/app
COPY ./dist/apps/api/ ./
COPY ./dist/apps/abi ../abi
COPY --from=deps /usr/src/app/node_modules ./node_modules
RUN npm run app:generate && \
    npm run news:generate

CMD [ "npm", "start" ]