{{- if .Values.ingress.enabled -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "giga-helm.name" . }}-ingress
  namespace: {{ default .Values.namespace .Release.Namespace }}
  labels:
    {{- include "giga-helm.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  # ingressClassName: azure-application-gateway
  # ingressClassName: nginx
  ingressClassName: traefik
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          - path: {{ $.Values.ingress.api.path }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $.Values.ingress.api.backendService }}
                port:
                  number: {{ $.Values.api.service.port }}
          - path: {{ $.Values.ingress.admin.path }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $.Values.ingress.admin.backendService }}
                port:
                  number: {{ $.Values.admin.service.port }}
          - path: {{ $.Values.ingress.web.path }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $.Values.ingress.web.backendService }}
                port:
                  number: {{ $.Values.web.service.port }}
          - path: {{ $.Values.ingress.webhook.path }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $.Values.ingress.webhook.backendService }}
                port:
                  number: {{ $.Values.webhook.service.port }}
{{- end }}