apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhook.fullname" . }}
  namespace: {{ default .Values.namespace .Release.Namespace }}
  labels:
    {{- toYaml .Values.webhook.labels | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.webhook.labels | nindent 4 }}
