{{- if .Values.ingress.enabled -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "giga-blocks.name" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "giga-blocks.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          - pathType: {{ $ingressPathType }}
            path: {{ $.Values.ingress.web.path }}
            backend:
              service:
                name: {{ $.Values.ingress.web.backendService }}
                port:
                  number: {{ $.Values.web.service.port }}
          - pathType: {{ $ingressPathType }}
            path: {{ $.Values.ingress.api.path }}
            backend:
              service:
                name: {{ $.Values.ingress.api.backendService }}
                port:
                  number: {{ $.Values.api.service.port }}
          - pathType: {{ $ingressPathType }}
            path: {{ $.Values.ingress.admin.path }}
            backend:
              service:
                name: {{ $.Values.ingress.admin.backendService }}
                port:
                  number: {{ $.Values.admin.service.port }}
          - pathType: {{ $ingressPathType }}
            path: {{ $.Values.ingress.docs.path }}
            backend:
              service:
                name: {{ $.Values.ingress.docs.backendService }}
                port:
                  number: 80
{{- end }}
