name: Stage Root CI/CD
on:
  push:
    branches:
      - 'stage'
  pull_request:
    branches:
      - 'stage'
  workflow_dispatch:

env:
  CI: false
  ADMIN_MANIFEST_FILE: 'K8s-Manifest/Giga/Stage/Argo-Rollout/admin.yaml'
  WEB_MANIFEST_FILE: 'K8s-Manifest/Giga/Stage/Argo-Rollout/web.yaml'
  API_MANIFEST_FILE: 'K8s-Manifest/Giga/Stage/Argo-Rollout/api.yaml'

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            github/data/general/docker/rumsan username | DOCKERHUB_USERNAME ;
            github/data/general/docker/rumsan password | DOCKERHUB_TOKEN ;
            github/data/giga/stage env | ENV ;

      - name: create environment file
        run: |
          tee ./.env <<<"$ENV"

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            github/data/general/docker/rumsan username | DOCKERHUB_USERNAME ;
            github/data/general/docker/rumsan password | DOCKERHUB_TOKEN ;
            github/data/giga/stage env | ENV ;

      - name: create environment file
        run: |
          tee ./.env <<<"$ENV"

      - uses: actions/setup-node@v3
        with:
          node-version: 20.13.1

      - name: install dependencies and build apps
        run: |
          npm install -g pnpm@8.14.1
          pnpm install
          pnpm run api:app:generate
          pnpm run api:news:generate
          pnpm build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # API Image
      - name: build && push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.api
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            rumsan/giga-mono-ntf2-api:stage
            rumsan/giga-mono-ntf2-api:stage-${{ steps.vars.outputs.sha_short }}

      # Admin Image
      - name: build && push admin
        id: build-push-admin
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.admin
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            rumsan/giga-mono-ntf2-admin:stage
            rumsan/giga-mono-ntf2-admin:stage-${{ steps.vars.outputs.sha_short }}

      #  Web Image
      - name: build && push web
        id: build-push-web
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.web
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            rumsan/giga-mono-ntf2-web:stage
            rumsan/giga-mono-ntf2-web:stage-${{ steps.vars.outputs.sha_short }}
<<<<<<< Updated upstream

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

=======

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

>>>>>>> Stashed changes
  update-manifest:
    name: Update Kubernetes Manifest
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            github/data/general/Stage-Manifest repo | MANIFEST_REPO ;
            github/data/general/Stage-Manifest ssh-key | SSH_KEY ;

      # Checkout the manifest repository using SSH
      - name: Checkout Stage Manifest Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFEST_REPO }}
          ssh-key: ${{ env.SSH_KEY }}

      # Update the image tag in the manifest
      - name: Update Image Tag in Manifest
        run: |
          sed -i "s|image: rumsan/giga-mono-ntf2-admin:.*|image: rumsan/giga-mono-ntf2-admin:stage-${{ steps.vars.outputs.sha_short }}|" ${{ env.ADMIN_MANIFEST_FILE }}
          sed -i "s|image: rumsan/giga-mono-ntf2-api:.*|image: rumsan/giga-mono-ntf2-api:stage-${{ steps.vars.outputs.sha_short }}|" ${{ env.API_MANIFEST_FILE }}
          sed -i "s|image: rumsan/giga-mono-ntf2-web:.*|image: rumsan/giga-mono-ntf2-web:stage-${{ steps.vars.outputs.sha_short }}|" ${{ env.WEB_MANIFEST_FILE }}

      # Commit and push changes using SSH
      - name: Commit and Push Changes
        run: |
          git config user.name "sandab-rumsan"
          git config user.email "sandab@rumsan.net"
          git add ${{ env.ADMIN_MANIFEST_FILE }}
          git add ${{ env.API_MANIFEST_FILE }}
          git add ${{ env.WEB_MANIFEST_FILE }}
          git commit -m "runner: Update Giga Stage image tag to stage-${{ needs.deploy.outputs.sha_short }}"
          git push origin main
